### ISSUE TITLE
Move markdown and edit makefile to load Rmd

### ISSUE THREAD

**Issue by Flip-Gootjes** [course-dprep/IMDb-Series-Rating-Investigation#84]

**Comment by FinnWong1108** [comment]
R -e "rmarkdown::render('Exploration.Rmd', output_file = '../../gen/output/Exploration.html')"

maybe try this one, i cant run in my laptop
and do we need PDF or html for rmd?

**Comment by GOikonomou25** [comment]
We can open a new issue to solve this problem today
